class_name RealData
extends RefCounted
## Real-world facts about the stations, digested by tools/fetch_station_real.py (TfL open data + OpenStreetMap, see CREDITS.md) and
## tools/fetch_platform_numbers.py (TfL live arrivals). Everything here is optional: a station without data keeps the generated values.

const STATIONS := "res://data/stations_real.json"
const PLATFORM_NUMBERS := "res://data/platform_numbers.json"
const LAYOUTS := "res://data/station_layouts.json"
const DERIVED_DEPTHS := "res://data/real_depths.json"      # depths from the platform levels for the stations without a measured one (tools/build_real_depths.py)
const SURFACE_PLATFORMS := "res://data/surface_platforms.json"      # the same for the other lines' generated surface stations, per line group (tools/build_surface_platforms.py)
const EL_PLATFORMS := "res://data/el_platforms.json"      # how the Elizabeth line's surface stations are laid out (side platforms or an island; tools/build_el_platforms.py)
const EL_DEPTHS := "res://data/elizabeth_depths.json"      # platform depths of the Elizabeth line (tools/build_elizabeth_depths.py), merged into the layouts' depths

static var _stations: Dictionary = {}
static var _numbers: Dictionary = {}
static var _layouts: Dictionary = {}
static var _loaded := false
static var _el_platforms: Dictionary = {}
static var _surface_platforms: Dictionary = {}
static var _el_loaded := false
static var _el_mx := Mutex.new()          # (plans are generated by worker threads too)


static func _load() -> void:
	if _loaded:
		return
	_loaded = true
	for pair in [[STATIONS, "_stations"], [PLATFORM_NUMBERS, "_numbers"], [LAYOUTS, "_layouts"]]:
		if FileAccess.file_exists(pair[0]):
			var f := FileAccess.open(pair[0], FileAccess.READ)
			var parsed = JSON.parse_string(f.get_as_text())
			if parsed is Dictionary:
				match pair[1]:
					"_stations":
						_stations = parsed
					"_numbers":
						_numbers = parsed
					_:
						_layouts = parsed
	if FileAccess.file_exists(DERIVED_DEPTHS):
		var fd := FileAccess.open(DERIVED_DEPTHS, FileAccess.READ)
		var dd = JSON.parse_string(fd.get_as_text())
		if dd is Dictionary:
			for nap in dd:
				if String(nap).begins_with("_"):
					continue
				var ent2: Dictionary = _layouts.get(nap, {})
				if not (ent2.get("depths", {}) as Dictionary).is_empty():
					continue          # (measured ones win)
				ent2["depths"] = dd[nap]["depths"]
				_layouts[nap] = ent2
	if FileAccess.file_exists(EL_DEPTHS):
		var fe := FileAccess.open(EL_DEPTHS, FileAccess.READ)
		var el = JSON.parse_string(fe.get_as_text())
		if el is Dictionary:
			for nap in el:
				if String(nap).begins_with("_"):
					continue
				var ent: Dictionary = _layouts.get(nap, {})
				var deps: Dictionary = ent.get("depths", {})
				for g in el[nap]["depths"]:
					deps[g] = el[nap]["depths"][g]
				ent["depths"] = deps
				_layouts[nap] = ent


## how the Elizabeth line's platforms at a surface station lie (data/el_platforms.json), or {}
static func el_platforms(naptan: String) -> Dictionary:
	_el_mx.lock()
	if not _el_loaded:
		if FileAccess.file_exists(EL_PLATFORMS):
			var f := FileAccess.open(EL_PLATFORMS, FileAccess.READ)
			var parsed = JSON.parse_string(f.get_as_text())
			if parsed is Dictionary:
				_el_platforms = parsed
		if FileAccess.file_exists(SURFACE_PLATFORMS):
			var f2 := FileAccess.open(SURFACE_PLATFORMS, FileAccess.READ)
			var parsed2 = JSON.parse_string(f2.get_as_text())
			if parsed2 is Dictionary:
				_surface_platforms = parsed2
		_el_loaded = true
	_el_mx.unlock()
	return _el_platforms.get(naptan, {})


## how the platforms of line group `group` ("elizabeth", "ss", "central" ...) lie at a generated surface station: {arrangement "side" | "island", gap, stagger, axis, footbridges ...} (the Elizabeth line's
## from data/el_platforms.json, the others' from data/surface_platforms.json), or {}
static func platform_layout(naptan: String, group: String) -> Dictionary:
	if group == "elizabeth":
		return el_platforms(naptan)
	el_platforms("")          # (loads both files)
	return ((_surface_platforms.get(naptan, {}) as Dictionary).get("groups", {}) as Dictionary).get(group, {})


## digest for a NaPTAN id, or {}
static func station(naptan: String) -> Dictionary:
	_load()
	return _stations.get(naptan, {})


## authored/measured layout facts for a station (depths in metres below street level per line group, ...), or {}
static func layout(naptan: String) -> Dictionary:
	_load()
	return _layouts.get(naptan, {})


## authored layout spec (data/layouts/<naptan>.json, see LayoutCompiler), or {}
static func layout_spec(naptan: String) -> Dictionary:
	var path := "res://data/layouts/%s.json" % naptan
	if not FileAccess.file_exists(path):
		return {}
	var f := FileAccess.open(path, FileAccess.READ)
	var parsed = JSON.parse_string(f.get_as_text())
	return parsed if parsed is Dictionary else {}


## real platform number for (line, direction) at a station, 0 if unknown
static func platform_number(naptan: String, line: String, direction: String) -> int:
	_load()
	var d: Dictionary = _numbers.get(naptan, {})
	var lst: Array = d.get("%s|%s" % [line, direction], [])
	if lst.is_empty():
		return 0
	var best := 1 << 30
	for n in lst:
		best = mini(best, int(n))
	return best


## entrances usable as street doors, sorted by their real exit number ({ref, name, exit_only})
static func entrances(naptan: String) -> Array:
	var out: Array = []
	for e in station(naptan).get("entrances", []):
		# OSM's search radius also catches neighbouring stations' entrances: keep only what is close to this station's centre
		if Vector2(float(e.get("e", 0.0)), float(e.get("n", 0.0))).length() > 130.0:
			continue
		if str(e.get("ref", "")) != "" or str(e.get("name", "")) != "":
			out.append(e)
	out.sort_custom(func(a, b):
		var ra := int(str(a.get("ref", "0")).to_int())
		var rb := int(str(b.get("ref", "0")).to_int())
		if ra != rb:
			return ra < rb
		return str(a.get("name", "")) < str(b.get("name", "")))
	return out


## "Exit 4, Oxford Street - West / Regent Street - North" -> "Oxford Street West / Regent Street North"
static func street_of(entrance: Dictionary) -> String:
	var n := str(entrance.get("name", ""))
	var comma := n.find(", ")
	if n.begins_with("Exit") and comma >= 0:
		n = n.substr(comma + 2)
	return n.replace(" - ", " ")
