class_name PlatformCurve
extends RefCounted
## Which platform modules are curved, and how much. A module is designed straight (its plan, rooms and walking graph are in "design space"); a curved one is wrapped round an arc afterwards (Bend):
## the part with the spine and the cross-passages stays straight, the platform beyond it follows the curve, and the running tunnel carries on straight at the heading the curve ended with.
##
## The curvature is real: data/line_geometry.json holds, for every platform and the direction a train leaves it, the heading change of the track across the platform (110 m, + = left in the
## direction of travel), measured from OpenStreetMap's track geometry (tools/build_line_geometry.py). The two faces of a module are one physical curve seen from both ways, so their figures are
## averaged. Gentle curves (under MIN_DH degrees across a platform) are left straight. UG_BEND=<radius in metres, negative turns the other way> bends every deep-tube module and UG_BEND=off bends none (tests).

const BEND_OPEN := true           # open-air platforms (canopy, retaining wall, backdrop) bend too
const BEND_BOX := true             # sub-surface / surface box halls bend too
const MIN_DH := 5.0                 # degrees across the platform
const MIN_RADIUS := 150.0           # the sharpest bend drawn (Bank's Central line platforms are about this tight)
const MIN_ARC := 40.0               # a curve shorter than this is not worth bending for

static var _next_cache: Dictionary = {}
static var _nb_cache: Dictionary = {}
static var _mx := Mutex.new()          # (plans are generated by worker threads too)


## the bend of module `mi` of `plan`: {} when straight, else {kappa, x0, x1, dh, source} in the module's design frame (x along the platform, the faces' tracks at +-z, + kappa turns toward -z)
static func for_module(plan: StationPlan, mi: int) -> Dictionary:
	var m: Dictionary = plan.modules[mi]
	var spec: Dictionary = m["spec"]
	if String(spec.get("style", "arch")) == "box" and (not BEND_BOX or (bool(spec.get("character", {}).get("open", false)) and not BEND_OPEN)):
		return {}
	var L: float = spec["length"]
	var x0: float = float(spec.get("spine_x1", -L * 0.5))
	var x1: float = L * 0.5
	if x1 - x0 < MIN_ARC:
		return {}
	var forced := OS.get_environment("UG_BEND")
	if forced == "off":                      # (UG_BEND=off: every platform straight, to compare audits)
		return {}
	var kappa := 0.0
	var dh := 0.0
	var source := "osm"
	if forced != "":
		kappa = 1.0 / forced.to_float()
		dh = rad_to_deg(kappa * 110.0)
		source = "forced"
	else:
		var sid: String = Net.station_ids[plan.idx]
		var sum := 0.0
		var n := 0
		var dsign: int = int(m.get("dir_sign", 1))
		for fi in (m["faces"] as Array).size():
			var fd: Dictionary = m["faces"][fi]
			var d := face_dh(sid, String(fd["pid"]))
			if is_nan(d):
				continue
			sum += d * float(dsign if fi == 0 else -dsign)          # (a face whose trains run toward -x: a left turn for them is a right turn along +x)
			n += 1
		if n == 0:
			return {}
		dh = sum / float(n)
		if absf(dh) < MIN_DH:
			return {}
		kappa = deg_to_rad(dh) / float(TrackPath.data().get("span", 110.0))
	var r := 1.0 / absf(kappa)
	if r < MIN_RADIUS:
		kappa = signf(kappa) / MIN_RADIUS
	var out := {"kappa": kappa, "x0": x0, "x1": x1, "dh": dh, "source": source}
	# the curve must have room: the stretch beyond the spine swings sideways (tens of metres for a tight one), so it must not run into another platform tunnel or room at its level.
	# The real turn direction is tried first, then the mirror image (the plan is a diagram: only the bend itself is real), and if neither fits the platform stays straight.
	if _conflicts(plan, mi, out):
		out["kappa"] = -kappa
		if _conflicts(plan, mi, out):
			return {}
		out["mirrored"] = true
	return out


## does the bent module (and its tunnel beyond the platform) hit another module's tunnel or a room at the same level?
static func _conflicts(plan: StationPlan, mi: int, bd: Dictionary) -> bool:
	var m: Dictionary = plan.modules[mi]
	var spec: Dictionary = m["spec"]
	var b := Bend.new(float(bd["kappa"]), float(bd["x0"]), float(bd["x1"]), 0.0)
	var pos: Vector3 = m["pos"]
	var y_lo := pos.y - 1.6
	var y_hi := pos.y + 4.6
	var x_end: float = float(spec["length"]) * 0.5 + float(spec.get("tun_e", PlatformModule.TUNNEL_EXT)) - 20.0
	var half_w := PlatformModule.half_width(float(spec["pw"])) + 0.8
	# obstacles: [x0, x1, z0, z1, y0, y1]
	var obs: Array = []
	for oi in plan.modules.size():
		if oi == mi:
			continue
		var om: Dictionary = plan.modules[oi]
		var os: Dictionary = om["spec"]
		var op: Vector3 = om["pos"]
		var ol: float = os["length"]
		var obend: Dictionary = om.get("bend", {})
		if not obend.is_empty():
			var ob := Bend.new(float(obend["kappa"]), float(obend["x0"]), float(obend["x1"]), 0.0)
			var ox_end: float = ol * 0.5 + float(os.get("tun_e", PlatformModule.TUNNEL_EXT)) - 20.0
			var ox := float(os["spine_x0"])
			while ox <= ox_end:
				var oc := op + ob.map(Vector3(ox, 0.0, 0.0))
				obs.append([oc.x - half_w, oc.x + half_w, oc.z - half_w, oc.z + half_w, op.y - 1.6, op.y + 4.6])
				ox += 4.0
		else:
			obs.append([op.x + float(os["spine_x0"]) - 1.0, op.x + ol * 0.5 + float(os.get("tun_e", PlatformModule.TUNNEL_EXT)), op.z - 8.6, op.z + 8.6, op.y - 1.6, op.y + 4.6])
	for rm in plan.rooms:
		var rn: String = rm["name"]
		if rn.begins_with("street_passage") or not rm.has("rect"):
			continue
		var r: Array = rm["rect"]
		var ry: float = float(rm.get("y", 0.0))
		if rn == "corridor%d_%d" % [m.get("level", 0), mi]:
			continue
		obs.append([r[0], r[1], r[2], r[3], ry - 0.4, ry + float(rm.get("h", 4.0)) + 0.4])
	for ei in plan.escs.size():
		var e: Dictionary = plan.escs[ei]
		if e.get("removed", false):
			continue
		var len_e: float = e["length"]
		var rise_e: float = e["rise"]
		var t := 0.0
		while t <= len_e + 0.1:
			var q: Vector3 = plan.esc_point(ei, Vector3(t, -rise_e * t / maxf(len_e, 0.1), 0.0))
			var hw: float = float(e["width"]) * 0.5 + 0.6
			obs.append([q.x - hw, q.x + hw, q.z - hw, q.z + hw, q.y - 1.0, q.y + 4.0])
			t += 2.0
	var x := float(bd["x0"]) + 2.0
	while x <= x_end:
		var c := pos + b.map(Vector3(x, 0.0, 0.0))
		for o in obs:
			if y_hi < o[4] or y_lo > o[5]:
				continue
			if c.x + half_w > o[0] and c.x - half_w < o[1] and c.z + half_w > o[2] and c.z - half_w < o[3]:
				return true
		x += 4.0
	return false


## which way the trains of a module run along it: +1 when face 0's trains run toward +x with the platform on their LEFT (the doors open on the left), -1 when they run toward -x and the
## platform is on their RIGHT. The sides come from where the platform outlines lie beside the track in OpenStreetMap (data/line_geometry.json); where there are none the platform stays on the left.
static func dir_sign_for(plan: StationPlan, mi: int) -> int:
	var sid: String = Net.station_ids[plan.idx]
	var votes := 0
	for fd in plan.modules[mi]["faces"]:
		var sd := face_side(sid, String(fd["pid"]))
		if sd == "R":
			votes -= 1
		elif sd == "L":
			votes += 1
	return -1 if votes < 0 else 1


## "L", "R" or "B" (both sides) / "" (unknown): on which side of the train, looking the way it goes, the platform at `pid` of station `sid` lies
static func face_side(sid: String, pid: String) -> String:
	var plats: Dictionary = TrackPath.data().get("platforms", {})
	if not plats.has(sid):
		return ""
	var nx := _next_station(sid, pid)
	if nx == "" or not (plats[sid] as Dictionary).has(nx):
		return ""
	return String(plats[sid][nx].get("side", ""))


## the heading change (degrees across the platform, + = left) of the track at platform `pid` of station `sid` in the direction the trains leave it; NAN when the data has none
static func face_dh(sid: String, pid: String) -> float:
	var plats: Dictionary = TrackPath.data().get("platforms", {})
	if not plats.has(sid):
		return NAN
	var nx := _next_station(sid, pid)
	if nx == "" or not (plats[sid] as Dictionary).has(nx):
		return NAN
	return float(plats[sid][nx].get("dh", NAN))


## the station the trains leave platform `pid` of station `sid` for (a service that calls there and uses it, going forward or back)
static func _next_station(sid: String, pid: String) -> String:
	var key := sid + "|" + pid
	_mx.lock()
	var hit: bool = _next_cache.has(key)
	var cached: String = _next_cache.get(key, "")
	_mx.unlock()
	if hit:
		return cached
	var out := ""
	for l in Net.lines:
		for svc in Net.lines[l]["services"]:
			var stops: Array = svc["stops"]
			for i in stops.size():
				if stops[i] != sid:
					continue
				if svc["plat_fwd"][i] == pid and i + 1 < stops.size():
					out = stops[i + 1]
				elif svc["plat_bwd"][i] == pid and i > 0:
					out = stops[i - 1]
				if out != "":
					break
			if out != "":
				break
		if out != "":
			break
	_mx.lock()
	_next_cache[key] = out
	_mx.unlock()
	return out


## [previous, next]: the stations the trains of platform `pid` of station `sid` come from and leave for ("" for none: a terminus, or no service found)
static func neighbours(sid: String, pid: String) -> Array:
	var key := sid + "|" + pid
	_mx.lock()
	var hit: bool = _nb_cache.has(key)
	var cached: Array = _nb_cache.get(key, [])
	_mx.unlock()
	if hit:
		return cached
	var out := ["", ""]
	for l in Net.lines:
		for svc in Net.lines[l]["services"]:
			var stops: Array = svc["stops"]
			for i in stops.size():
				if stops[i] != sid:
					continue
				var fwd: bool = svc["plat_fwd"][i] == pid
				var bwd: bool = svc["plat_bwd"][i] == pid
				if not fwd and not bwd:
					continue
				var before: String = stops[i - 1] if i > 0 else ""
				var after: String = stops[i + 1] if i + 1 < stops.size() else ""
				var pv := before if fwd else after
				var nx := after if fwd else before
				if out[0] == "":
					out[0] = pv
				if out[1] == "":
					out[1] = nx
			if out[0] != "" and out[1] != "":
				break
		if out[0] != "" and out[1] != "":
			break
	_mx.lock()
	_nb_cache[key] = out
	_mx.unlock()
	return out
