class_name TrackPath
extends RefCounted
## The track between two stations as a ride sees it, seen from the train that sets off: a flat centre line in the frame of the train at distance 0 (x = the way it travels, z = to its right,
## y up), made of cells of CELL metres each with a constant curvature, so a pose at any distance along it is closed form and a scenery cell is exactly one arc.
## Cell k is centred at s = k * CELL (cell 0 spans -6..6 m) and curves by the curvature of its entry (1/m, + = turning left: +x swings toward -z, like Bend); the cells run from `k_first()` (BACK cells before the
## starting point: the platform behind the train, where its rear cars stand) to `k_last()` (past the end: the platform ahead of the train when it has stopped). Beyond them the track is straight.
## The real heading profile of the line (data/line_geometry.json, from OpenStreetMap) is where the curvature comes from; it is held at zero near both stations (`fade_in` / `fade_out`), where the
## platform and its running tunnel are straight.

const CELL := 12.0
const Q := 1.0 / 1500.0              # curvature step of the scenery meshes (a mesh is built per step)
const MAX_CLASS := 14                # R = 107 m
const BACK := 14                     # cells before the start (168 m): the platform behind the train and the rear cars
const AHEAD := 14                    # cells past the end
const RAMP := 36.0                   # the curvature is faded in / out over this many metres
const DATA := "res://data/line_geometry.json"

static var _data: Dictionary = {}
static var _loaded := false
static var _mx := Mutex.new()          # (plans are generated by worker threads too: the shared data is loaded once, under this lock)

var kappa := PackedFloat32Array()    # per cell, from k_first()
var length := 0.0                    # distance from the origin station's stop to the destination's
var _kmin := 0                       # index of the first cell
var _anchor := Transform3D.IDENTITY  # puts the raw (first cell's) frame where the frame of the path is: pose(0) is the identity
var _th := PackedFloat32Array()      # heading at the start of each cell (n + 1 values), in the raw frame
var _p := PackedVector3Array()       # position at the start of each cell (n + 1 values)


static func data() -> Dictionary:
	_mx.lock()
	if not _loaded:
		var f := FileAccess.open(DATA, FileAccess.READ)
		if f != null:
			_data = JSON.parse_string(f.get_as_text())
		_loaded = true
	_mx.unlock()
	return _data


## the path of the track from station `a` to station `b` (NaPTAN ids) as the train sets off from a (distance 0 = where its centre stands), `dist` metres long.
## Without data for the pair, a straight path. `head` / `tail` are the exact curves of curved platforms at the two ends, [[length, curvature], ...] in the direction of travel: `head` from distance 0,
## `tail` ending at `dist` (they replace the real profile there; the fades keep the profile off their neighbourhood).
static func between(a: String, b: String, dist: float, fade_in: float, fade_out: float, head: Array = [], tail: Array = [], back: Array = [], after: Array = []) -> TrackPath:
	var h: Array = profile(a, b)
	var tp := TrackPath.new()
	tp.length = dist
	var kmin := -BACK
	var kmax := int(ceil((dist + 6.0) / CELL)) + AHEAD
	var n := kmax - kmin + 1
	var ks := PackedFloat32Array()
	ks.resize(n)
	var forced := OS.get_environment("UG_CURVE")          # (tests: UG_CURVE=<class> bends every ride at a constant R = 1500 / class, whatever the data says)
	if forced != "" or h.is_empty():
		if forced != "":
			for i in n:
				var sc := float(kmin + i) * CELL
				var w := smoothstep(fade_in, fade_in + RAMP, sc) * (1.0 - smoothstep(dist - fade_out - RAMP, dist - fade_out, sc))
				ks[i] = roundf(float(forced.to_int()) * w) * Q
		_overlay(ks, kmin, head, tail, back, after, dist)
		tp._build(ks, dist, kmin)
		return tp
	var real_len: float = h[0]
	var hs: Array = h[1]
	var step: float = data().get("step", 20.0)
	for i in n:
		var k := kmin + i
		var s0 := float(k) * CELL - CELL * 0.5
		var s1 := s0 + CELL
		# distance along the real track that this cell covers (the ride length may differ a little from the real one)
		var d0 := clampf(s0, 0.0, dist) * real_len / dist
		var d1 := clampf(s1, 0.0, dist) * real_len / dist
		var dh := _heading_at(hs, step, real_len, d1) - _heading_at(hs, step, real_len, d0)
		var kk := dh / maxf(CELL * real_len / dist, 0.001)
		var sc := float(k) * CELL
		var w := smoothstep(fade_in, fade_in + RAMP, sc) * (1.0 - smoothstep(dist - fade_out - RAMP, dist - fade_out, sc))
		var cls := clampi(int(roundf(kk * w / Q)), -MAX_CLASS, MAX_CLASS)
		ks[i] = cls * Q
	_overlay(ks, kmin, head, tail, back, after, dist)
	tp._build(ks, dist, kmin)
	return tp


## the exact curves of the platforms at both ends replace the profile where they lie: `back` ends at distance 0 and `head` starts there (the platform behind and ahead of the train that sets off),
## `tail` ends at `dist` and `after` starts there (the platform behind and ahead of the train that has stopped); each is [[length, curvature], ...] in the direction of travel
static func _overlay(ks: PackedFloat32Array, kmin: int, head: Array, tail: Array, back: Array, after: Array, dist: float) -> void:
	if head.is_empty() and tail.is_empty() and back.is_empty() and after.is_empty():
		return
	var cover := PackedFloat32Array()
	cover.resize(ks.size())
	var sum := PackedFloat32Array()
	sum.resize(ks.size())
	var segs: Array = []
	var s := 0.0
	for g in head:
		segs.append([s, s + float(g[0]), float(g[1])])
		s += float(g[0])
	var bl := 0.0
	for g in back:
		bl += float(g[0])
	s = -bl
	for g in back:
		segs.append([s, s + float(g[0]), float(g[1])])
		s += float(g[0])
	var tl := 0.0
	for g in tail:
		tl += float(g[0])
	s = dist - tl
	for g in tail:
		segs.append([s, s + float(g[0]), float(g[1])])
		s += float(g[0])
	s = dist
	for g in after:
		segs.append([s, s + float(g[0]), float(g[1])])
		s += float(g[0])
	for sg in segs:
		var k0 := maxi(kmin, int(floor((sg[0] + CELL * 0.5) / CELL)))
		var k1 := mini(kmin + ks.size() - 1, int(floor((sg[1] + CELL * 0.5) / CELL)))
		for k in range(k0, k1 + 1):
			var c0 := float(k) * CELL - CELL * 0.5
			var ov := minf(sg[1], c0 + CELL) - maxf(sg[0], c0)
			if ov > 0.0:
				cover[k - kmin] += ov / CELL
				sum[k - kmin] += ov / CELL * sg[2]
	for i in ks.size():
		if cover[i] > 0.0:
			ks[i] = ks[i] * maxf(0.0, 1.0 - cover[i]) + sum[i]


## [real length, headings in radians at 0, step, 2 step ... length] of the track from a to b, or [] when unknown. Falls back to the other direction's track, reversed.
static func profile(a: String, b: String) -> Array:
	var pairs: Dictionary = data().get("pairs", {})
	var e: Dictionary = pairs.get(a + ">" + b, {})
	if not e.is_empty():
		var hs: Array = []
		for v in e["h"]:
			hs.append(deg_to_rad(float(v) / 10.0))
		return [float(e["len"]), hs]
	e = pairs.get(b + ">" + a, {})
	if e.is_empty():
		return []
	# the same track travelled the other way: heading(s) = h(len - s) - h(len)
	var raw: Array = e["h"]
	var step: float = data().get("step", 20.0)
	var L: float = e["len"]
	var hl := deg_to_rad(float(raw[raw.size() - 1]) / 10.0)
	var n := int(floor(L / step))
	var hs2: Array = []
	for i in n + 1:
		hs2.append(_heading_at_raw(raw, step, L, L - float(i) * step) - hl)
	var tail := L - float(n) * step
	if tail > 1.0:
		hs2.append(_heading_at_raw(raw, step, L, 0.0) - hl)
	return [L, hs2]


static func _heading_at_raw(raw: Array, step: float, L: float, s: float) -> float:
	var hs: Array = []
	for v in raw:
		hs.append(deg_to_rad(float(v) / 10.0))
	return _heading_at(hs, step, L, s)


## heading at distance s from samples every `step` metres (the last one at `L`)
static func _heading_at(hs: Array, step: float, L: float, s: float) -> float:
	s = clampf(s, 0.0, L)
	var n := hs.size()
	var full := int(floor(L / step))               # samples 0..full are on the step grid; a last one (if any) is at L
	var i := mini(int(floor(s / step)), full)
	if i >= n - 1:
		return hs[n - 1]
	var s0 := float(i) * step
	var s1 := float(i + 1) * step if i + 1 <= full else L
	return lerpf(hs[i], hs[i + 1], clampf((s - s0) / maxf(s1 - s0, 0.001), 0.0, 1.0))


func _build(ks: PackedFloat32Array, dist: float, kmin := 0) -> void:
	length = dist
	kappa = ks
	_kmin = kmin
	var n := kappa.size()
	_th.resize(n + 1)
	_p.resize(n + 1)
	_th[0] = 0.0
	_p[0] = Vector3.ZERO
	for i in n:
		var q := _step(_th[i], _p[i], kappa[i], CELL)
		_th[i + 1] = q[0]
		_p[i + 1] = q[1]
	# the frame of the path is the one the track has at distance 0
	_anchor = Transform3D.IDENTITY
	_anchor = _raw_pose(0.0).affine_inverse()


## heading and position after u metres of curvature kk from heading th0 at p0
static func _step(th0: float, p0: Vector3, kk: float, u: float) -> Array:
	if absf(kk) < 1e-9:
		return [th0, p0 + Vector3(cos(th0), 0.0, -sin(th0)) * u]
	var th1 := th0 + kk * u
	return [th1, p0 + Vector3((sin(th1) - sin(th0)) / kk, 0.0, (cos(th1) - cos(th0)) / kk)]


func is_straight() -> bool:
	for k in kappa:
		if absf(k) > 1e-9:
			return false
	return true


func cell_count() -> int:
	return kappa.size()


## the first and the last cell index
func k_first() -> int:
	return _kmin


func k_last() -> int:
	return _kmin + kappa.size() - 1


## the curvature class (-MAX_CLASS..MAX_CLASS) of the cell centred at k * CELL
func cell_class(k: int) -> int:
	var i := k - _kmin
	if i < 0 or i >= kappa.size():
		return 0
	return int(roundf(kappa[i] / Q))


func _raw_pose(s: float) -> Transform3D:
	var n := kappa.size()
	var s_start := float(_kmin) * CELL - CELL * 0.5
	var i := int(floor((s - s_start) / CELL))
	if i < 0:
		return Transform3D(Basis.IDENTITY, Vector3(s - s_start, 0.0, 0.0))
	if i >= n:
		var th := _th[n]
		return Transform3D(Basis(Vector3.UP, th), _p[n] + Vector3(cos(th), 0.0, -sin(th)) * (s - s_start - float(n) * CELL))
	var q := _step(_th[i], _p[i], kappa[i], s - s_start - float(i) * CELL)
	return Transform3D(Basis(Vector3.UP, q[0]), q[1])


## the pose of the track at distance s: origin on the centre line at the path's level 0, +x along the track, +z to the right
func pose(s: float) -> Transform3D:
	return _anchor * _raw_pose(s)


## heading of the track at distance s relative to the start (radians, + = left)
func theta(s: float) -> float:
	return _theta_raw(s) - _theta_raw(0.0)


func _theta_raw(s: float) -> float:
	var n := kappa.size()
	var s_start := float(_kmin) * CELL - CELL * 0.5
	var i := int(floor((s - s_start) / CELL))
	if i < 0:
		return 0.0
	if i >= n:
		return _th[n]
	return _th[i] + kappa[i] * (s - s_start - float(i) * CELL)
