class_name TrackPath
extends RefCounted
## The track between two stations as a ride sees it, seen from the train that sets off: a flat centre line in the frame of the train at distance 0 (x = the way it travels, z = to its right,
## y up), made of cells of CELL metres each with a constant curvature, so a pose at any distance along it is closed form and a scenery cell is exactly one arc.
## Cell k is centred at s = k * CELL (cell 0 spans -6..6 m) and curves by `kappa[k]` (1/m, + = turning left: +x swings toward -z, like Bend). Before cell 0 and after the last cell the track is straight.
## The real heading profile of the line (data/line_geometry.json, from OpenStreetMap) is where the curvature comes from; it is held at zero near both stations (`fade_in` / `fade_out`), where the
## platform and its running tunnel are straight.

const CELL := 12.0
const Q := 1.0 / 1500.0              # curvature step of the scenery meshes (a mesh is built per step)
const MAX_CLASS := 14                # R = 107 m
const RAMP := 36.0                   # the curvature is faded in / out over this many metres
const DATA := "res://data/line_geometry.json"

static var _data: Dictionary = {}
static var _loaded := false
static var _mx := Mutex.new()          # (plans are generated by worker threads too: the shared data is loaded once, under this lock)

var kappa := PackedFloat32Array()    # per cell
var length := 0.0                    # distance from the origin station's stop to the destination's
var _th := PackedFloat32Array()      # heading at the start of each cell (n + 1 values)
var _p := PackedVector3Array()       # position at the start of each cell (n + 1 values)


static func data() -> Dictionary:
	_mx.lock()
	if not _loaded:
		var f := FileAccess.open(DATA, FileAccess.READ)
		if f != null:
			_data = JSON.parse_string(f.get_as_text())
		_loaded = true
	_mx.unlock()
	return _data


## the path of the track from station `a` to station `b` (NaPTAN ids) as the train sets off from a (distance 0 = where its centre stands), `dist` metres long.
## Without data for the pair, a straight path. `head` / `tail` are the exact curves of curved platforms at the two ends, [[length, curvature], ...] in the direction of travel: `head` from distance 0,
## `tail` ending at `dist` (they replace the real profile there; the fades keep the profile off their neighbourhood).
static func between(a: String, b: String, dist: float, fade_in: float, fade_out: float, head: Array = [], tail: Array = []) -> TrackPath:
	var h: Array = profile(a, b)
	var tp := TrackPath.new()
	tp.length = dist
	var forced := OS.get_environment("UG_CURVE")          # (tests: UG_CURVE=<class> bends every ride at a constant R = 1500 / class, whatever the data says)
	if forced != "":
		var fk := PackedFloat32Array()
		for k in int(ceil((dist + CELL) / CELL)) + 2:
			var sc := float(k) * CELL
			var w := smoothstep(fade_in, fade_in + RAMP, sc) * (1.0 - smoothstep(dist - fade_out - RAMP, dist - fade_out, sc))
			fk.append(roundf(float(forced.to_int()) * w) * Q)
		tp._build(fk, dist)
		return tp
	if h.is_empty():
		var ks0 := PackedFloat32Array()
		ks0.resize(int(ceil((dist + CELL) / CELL)) + 2)
		_overlay(ks0, head, tail, dist)
		tp._build(ks0, dist)
		return tp
	var real_len: float = h[0]
	var hs: Array = h[1]
	var step: float = data().get("step", 20.0)
	var n := int(ceil((dist + CELL) / CELL)) + 2
	var ks := PackedFloat32Array()
	ks.resize(n)
	for k in n:
		var s0 := float(k) * CELL - CELL * 0.5
		var s1 := s0 + CELL
		# distance along the real track that this cell covers (the ride length may differ a little from the real one)
		var d0 := clampf(s0, 0.0, dist) * real_len / dist
		var d1 := clampf(s1, 0.0, dist) * real_len / dist
		var dh := _heading_at(hs, step, real_len, d1) - _heading_at(hs, step, real_len, d0)
		var kk := dh / maxf(CELL * real_len / dist, 0.001)
		var sc := float(k) * CELL
		var w := smoothstep(fade_in, fade_in + RAMP, sc) * (1.0 - smoothstep(dist - fade_out - RAMP, dist - fade_out, sc))
		var cls := clampi(int(roundf(kk * w / Q)), -MAX_CLASS, MAX_CLASS)
		ks[k] = cls * Q
	_overlay(ks, head, tail, dist)
	tp._build(ks, dist)
	return tp


## the exact curves of the platforms at both ends replace the profile where they lie
static func _overlay(ks: PackedFloat32Array, head: Array, tail: Array, dist: float) -> void:
	if head.is_empty() and tail.is_empty():
		return
	var cover := PackedFloat32Array()
	cover.resize(ks.size())
	var sum := PackedFloat32Array()
	sum.resize(ks.size())
	var segs: Array = []
	var s := 0.0
	for g in head:
		segs.append([s, s + float(g[0]), float(g[1])])
		s += float(g[0])
	var tl := 0.0
	for g in tail:
		tl += float(g[0])
	s = dist - tl
	for g in tail:
		segs.append([s, s + float(g[0]), float(g[1])])
		s += float(g[0])
	for sg in segs:
		var k0 := maxi(0, int(floor((sg[0] + CELL * 0.5) / CELL)))
		var k1 := mini(ks.size() - 1, int(floor((sg[1] + CELL * 0.5) / CELL)))
		for k in range(k0, k1 + 1):
			var c0 := float(k) * CELL - CELL * 0.5
			var ov := minf(sg[1], c0 + CELL) - maxf(sg[0], c0)
			if ov > 0.0:
				cover[k] += ov / CELL
				sum[k] += ov / CELL * sg[2]
	for k in ks.size():
		if cover[k] > 0.0:
			ks[k] = ks[k] * maxf(0.0, 1.0 - cover[k]) + sum[k]


## [real length, headings in radians at 0, step, 2 step ... length] of the track from a to b, or [] when unknown. Falls back to the other direction's track, reversed.
static func profile(a: String, b: String) -> Array:
	var pairs: Dictionary = data().get("pairs", {})
	var e: Dictionary = pairs.get(a + ">" + b, {})
	if not e.is_empty():
		var hs: Array = []
		for v in e["h"]:
			hs.append(deg_to_rad(float(v) / 10.0))
		return [float(e["len"]), hs]
	e = pairs.get(b + ">" + a, {})
	if e.is_empty():
		return []
	# the same track travelled the other way: heading(s) = h(len - s) - h(len)
	var raw: Array = e["h"]
	var step: float = data().get("step", 20.0)
	var L: float = e["len"]
	var hl := deg_to_rad(float(raw[raw.size() - 1]) / 10.0)
	var n := int(floor(L / step))
	var hs2: Array = []
	for i in n + 1:
		hs2.append(_heading_at_raw(raw, step, L, L - float(i) * step) - hl)
	var tail := L - float(n) * step
	if tail > 1.0:
		hs2.append(_heading_at_raw(raw, step, L, 0.0) - hl)
	return [L, hs2]


static func _heading_at_raw(raw: Array, step: float, L: float, s: float) -> float:
	var hs: Array = []
	for v in raw:
		hs.append(deg_to_rad(float(v) / 10.0))
	return _heading_at(hs, step, L, s)


## heading at distance s from samples every `step` metres (the last one at `L`)
static func _heading_at(hs: Array, step: float, L: float, s: float) -> float:
	s = clampf(s, 0.0, L)
	var n := hs.size()
	var full := int(floor(L / step))               # samples 0..full are on the step grid; a last one (if any) is at L
	var i := mini(int(floor(s / step)), full)
	if i >= n - 1:
		return hs[n - 1]
	var s0 := float(i) * step
	var s1 := float(i + 1) * step if i + 1 <= full else L
	return lerpf(hs[i], hs[i + 1], clampf((s - s0) / maxf(s1 - s0, 0.001), 0.0, 1.0))


func _build(ks: PackedFloat32Array, dist: float) -> void:
	length = dist
	kappa = ks
	var n := kappa.size()
	_th.resize(n + 1)
	_p.resize(n + 1)
	_th[0] = 0.0
	_p[0] = Vector3(-CELL * 0.5, 0.0, 0.0)
	for k in n:
		var q := _step(_th[k], _p[k], kappa[k], CELL)
		_th[k + 1] = q[0]
		_p[k + 1] = q[1]


## heading and position after u metres of curvature kk from heading th0 at p0
static func _step(th0: float, p0: Vector3, kk: float, u: float) -> Array:
	if absf(kk) < 1e-9:
		return [th0, p0 + Vector3(cos(th0), 0.0, -sin(th0)) * u]
	var th1 := th0 + kk * u
	return [th1, p0 + Vector3((sin(th1) - sin(th0)) / kk, 0.0, (cos(th1) - cos(th0)) / kk)]


func is_straight() -> bool:
	for k in kappa:
		if absf(k) > 1e-9:
			return false
	return true


func cell_count() -> int:
	return kappa.size()


## the curvature class (-MAX_CLASS..MAX_CLASS) of the cell centred at k * CELL
func cell_class(k: int) -> int:
	if k < 0 or k >= kappa.size():
		return 0
	return int(roundf(kappa[k] / Q))


## the pose of the track at distance s: origin on the centre line at rail-head level 0, +x along the track, +z to the right
func pose(s: float) -> Transform3D:
	var n := kappa.size()
	var k := int(floor((s + CELL * 0.5) / CELL))
	if k < 0:
		return Transform3D(Basis.IDENTITY, Vector3(s, 0.0, 0.0))
	if k >= n:
		var th := _th[n]
		return Transform3D(Basis(Vector3.UP, th), _p[n] + Vector3(cos(th), 0.0, -sin(th)) * (s - (float(n) * CELL - CELL * 0.5)))
	var q := _step(_th[k], _p[k], kappa[k], s - (float(k) * CELL - CELL * 0.5))
	return Transform3D(Basis(Vector3.UP, q[0]), q[1])


## heading of the track at distance s relative to the start (radians, + = left)
func theta(s: float) -> float:
	var n := kappa.size()
	var k := int(floor((s + CELL * 0.5) / CELL))
	if k < 0:
		return 0.0
	if k >= n:
		return _th[n]
	return _th[k] + kappa[k] * (s - (float(k) * CELL - CELL * 0.5))
