class_name TrackPath
extends RefCounted
## The track between two stations as a ride sees it, seen from the train that sets off: a flat centre line in the frame of the train at distance 0 (x = the way it travels, z = to its right,
## y up), made of cells of CELL metres each with a constant curvature, so a pose at any distance along it is closed form and a scenery cell is exactly one arc.
## Cell k is centred at s = k * CELL (cell 0 spans -6..6 m) and curves by the curvature of its entry (1/m, + = turning left: +x swings toward -z, like Bend); the cells run from `k_first()` (BACK cells before the
## starting point: the platform behind the train, where its rear cars stand) to `k_last()` (past the end: the platform ahead of the train when it has stopped). Beyond them the track is straight.
## The real heading profile of the line (data/line_geometry.json, from OpenStreetMap) is where the curvature comes from; it is held at zero near both stations (`fade_in` / `fade_out`), where the
## platform and its running tunnel are straight.

const CELL := 12.0
const Q := 1.0 / 1500.0              # curvature step of the scenery meshes (a mesh is built per step)
const MAX_CLASS := 14                # R = 107 m
const BACK := 14                     # cells before the start (168 m): the platform behind the train and the rear cars
const AHEAD := 14                    # cells past the end
const RAMP := 36.0                   # the curvature is faded in / out over this many metres
const DATA := "res://data/line_geometry.json"
const MAX_GRADE := 0.045             # no stretch climbs or dips more steeply than this (1 : 22)

static var _data: Dictionary = {}
static var _loaded := false
static var _mx := Mutex.new()          # (plans are generated by worker threads too: the shared data is loaded once, under this lock)

var kappa := PackedFloat32Array()    # per cell, from k_first()
var length := 0.0                    # distance from the origin station's stop to the destination's
var _kmin := 0                       # index of the first cell
var _anchor := Transform3D.IDENTITY  # puts the raw (first cell's) frame where the frame of the path is: pose(0) is the identity
var _th := PackedFloat32Array()      # heading at the start of each cell (n + 1 values), in the raw frame
var _p := PackedVector3Array()       # position at the start of each cell (n + 1 values)
var single := false                  # the track is a single one (data/single_track.json): no second track beside it
var ss := false                      # a sub-surface line: its tunnels are cut-and-cover boxes
var _line := "elizabeth"             # the line of the ride (a station may be a pair of side platforms for one group and not for another, and a platform's group is not always its line's: StationPlan.group_of)
var secs: Array = []                 # what the track runs through, [[sec code, metres], ...] (data "sec": 0 open, 1 tunnel, 2 cutting, 3 embankment, 4 viaduct), scaled to the ride's length
var _scenes := PackedInt32Array()    # per cell, from k_first(): RunScenery's scene number
var pitch := PackedFloat32Array()    # per cell, from k_first(): the climb of the track (radians, + = up); the tunnels between deep stations dip between them
var _plan_pitch := PackedFloat32Array()      # (set before _build)
var _py := PackedFloat32Array()      # height of the track at the start of each cell


static func data() -> Dictionary:
	_mx.lock()
	if not _loaded:
		var f := FileAccess.open(DATA, FileAccess.READ)
		if f != null:
			_data = JSON.parse_string(f.get_as_text())
		_loaded = true
	_mx.unlock()
	return _data


const SINGLE := "res://data/single_track.json"
static var _single: Dictionary = {}
static var _single_loaded := false


## is the track between the stations a and b (NaPTAN ids) single (data/single_track.json): no second track beside it
static func is_single(a: String, b: String) -> bool:
	_mx.lock()
	if not _single_loaded:
		var f := FileAccess.open(SINGLE, FileAccess.READ)
		if f != null:
			var d: Dictionary = JSON.parse_string(f.get_as_text())
			for pr in d.get("pairs", []):
				_single[String(pr[0]) + ">" + String(pr[1])] = true
				_single[String(pr[1]) + ">" + String(pr[0])] = true
		_single_loaded = true
	_mx.unlock()
	return _single.has(a + ">" + b)


## the path of the track from station `a` to station `b` (NaPTAN ids) as the train sets off from a (distance 0 = where its centre stands), `dist` metres long.
## Without data for the pair, a straight path. `head` / `tail` are the exact curves of curved platforms at the two ends, [[length, curvature], ...] in the direction of travel: `head` from distance 0,
## `tail` ending at `dist` (they replace the real profile there; the fades keep the profile off their neighbourhood).
static func between(a: String, b: String, dist: float, fade_in: float, fade_out: float, head: Array = [], tail: Array = [], back: Array = [], after: Array = [], p_ss := false, v_pad_in := 0.0, v_pad_out := 0.0, p_line := "") -> TrackPath:
	var h: Array = profile(a, b)
	var tp := TrackPath.new()
	tp.length = dist
	var kmin := -BACK
	var kmax := int(ceil((dist + 6.0) / CELL)) + AHEAD
	tp.ss = p_ss
	tp._line = p_line if p_line != "" else "elizabeth"
	tp._set_scenes(a, b, dist, kmin, kmax, h)
	tp._plan_pitch = tp._plan_grade(a, b, p_line, dist, fade_in + v_pad_in, fade_out + v_pad_out, kmin, kmax)
	var n := kmax - kmin + 1
	var ks := PackedFloat32Array()
	ks.resize(n)
	var forced := OS.get_environment("UG_CURVE")          # (tests: UG_CURVE=<class> bends every ride at a constant R = 1500 / class, whatever the data says)
	if forced != "" or h.is_empty():
		if forced != "":
			for i in n:
				var sc := float(kmin + i) * CELL
				var w := smoothstep(fade_in, fade_in + RAMP, sc) * (1.0 - smoothstep(dist - fade_out - RAMP, dist - fade_out, sc))
				ks[i] = roundf(float(forced.to_int()) * w) * Q
		_overlay(ks, kmin, head, tail, back, after, dist)
		tp._build(ks, dist, kmin)
		return tp
	var real_len: float = h[0]
	var hs: Array = h[1]
	var step: float = data().get("step", 20.0)
	for i in n:
		var k := kmin + i
		var s0 := float(k) * CELL - CELL * 0.5
		var s1 := s0 + CELL
		# distance along the real track that this cell covers (the ride length may differ a little from the real one)
		var d0 := clampf(s0, 0.0, dist) * real_len / dist
		var d1 := clampf(s1, 0.0, dist) * real_len / dist
		var dh := _heading_at(hs, step, real_len, d1) - _heading_at(hs, step, real_len, d0)
		var kk := dh / maxf(CELL * real_len / dist, 0.001)
		var sc := float(k) * CELL
		var w := smoothstep(fade_in, fade_in + RAMP, sc) * (1.0 - smoothstep(dist - fade_out - RAMP, dist - fade_out, sc))
		var cls := clampi(int(roundf(kk * w / Q)), -MAX_CLASS, MAX_CLASS)
		ks[i] = cls * Q
	_overlay(ks, kmin, head, tail, back, after, dist)
	tp._build(ks, dist, kmin)
	return tp


## the exact curves of the platforms at both ends replace the profile where they lie: `back` ends at distance 0 and `head` starts there (the platform behind and ahead of the train that sets off),
## `tail` ends at `dist` and `after` starts there (the platform behind and ahead of the train that has stopped); each is [[length, curvature], ...] in the direction of travel
static func _overlay(ks: PackedFloat32Array, kmin: int, head: Array, tail: Array, back: Array, after: Array, dist: float) -> void:
	if head.is_empty() and tail.is_empty() and back.is_empty() and after.is_empty():
		return
	var cover := PackedFloat32Array()
	cover.resize(ks.size())
	var sum := PackedFloat32Array()
	sum.resize(ks.size())
	var segs: Array = []
	var s := 0.0
	for g in head:
		segs.append([s, s + float(g[0]), float(g[1])])
		s += float(g[0])
	var bl := 0.0
	for g in back:
		bl += float(g[0])
	s = -bl
	for g in back:
		segs.append([s, s + float(g[0]), float(g[1])])
		s += float(g[0])
	var tl := 0.0
	for g in tail:
		tl += float(g[0])
	s = dist - tl
	for g in tail:
		segs.append([s, s + float(g[0]), float(g[1])])
		s += float(g[0])
	s = dist
	for g in after:
		segs.append([s, s + float(g[0]), float(g[1])])
		s += float(g[0])
	for sg in segs:
		var k0 := maxi(kmin, int(floor((sg[0] + CELL * 0.5) / CELL)))
		var k1 := mini(kmin + ks.size() - 1, int(floor((sg[1] + CELL * 0.5) / CELL)))
		for k in range(k0, k1 + 1):
			var c0 := float(k) * CELL - CELL * 0.5
			var ov := minf(sg[1], c0 + CELL) - maxf(sg[0], c0)
			if ov > 0.0:
				cover[k - kmin] += ov / CELL
				sum[k - kmin] += ov / CELL * sg[2]
	for i in ks.size():
		if cover[i] > 0.0:
			ks[i] = ks[i] * maxf(0.0, 1.0 - cover[i]) + sum[i]


## what the track from a to b runs through, [[sec code, metres], ...] in that direction (the other direction's list reversed when only that one is known), or [] without data
static func sections(a: String, b: String) -> Array:
	# a hop has two entries when both directions are in the data (each from its own track): the ride one way and the station at the far end must read the SAME one, so the one of the pair that sorts first
	# is the source of both directions (reversed for the other)
	var pairs: Dictionary = data().get("pairs", {})
	var fwd: Dictionary = pairs.get(a + ">" + b, {})
	var rev: Dictionary = pairs.get(b + ">" + a, {})
	if a <= b and fwd.has("sec"):
		return (fwd["sec"] as Array).duplicate(true)
	if a > b and rev.has("sec"):
		var out: Array = (rev["sec"] as Array).duplicate(true)
		out.reverse()
		return out
	if fwd.has("sec"):
		return (fwd["sec"] as Array).duplicate(true)
	if rev.has("sec"):
		var out2: Array = (rev["sec"] as Array).duplicate(true)
		out2.reverse()
		return out2
	return []


## the waterways the hop's track crosses on a viaduct, [[metres from the stop, width], ...] (data "wat"; the same source pair as `sections`, reversed for the other direction)
static func water(a: String, b: String) -> Array:
	var pairs: Dictionary = data().get("pairs", {})
	var fwd: Dictionary = pairs.get(a + ">" + b, {})
	var rev: Dictionary = pairs.get(b + ">" + a, {})
	var use_rev: bool = (a > b and rev.has("sec")) or (not fwd.has("sec") and rev.has("sec"))
	var src: Dictionary = rev if use_rev else fwd
	var out: Array = []
	var length: float = float(src.get("len", 0.0))
	for w in src.get("wat", []):
		out.append([length - float(w[0]), float(w[1])] if use_rev else [float(w[0]), float(w[1])])
	out.sort_custom(func(x, y): return x[0] < y[0])
	return out


func _set_scenes(a: String, b: String, dist: float, kmin: int, kmax: int, prof: Array) -> void:
	var raw := sections(a, b)
	var real_len := 0.0
	for r in raw:
		real_len += float(r[1])
	if real_len < 1.0:
		real_len = float(prof[0]) if not prof.is_empty() else dist
	secs = []
	# The ride is `dist` long, the track on the ground real_len (the ride's length is clamped and re-solved from the timetable). A station draws the stretch beyond its platform from the real
	# lengths, so near both ends the ride must put the sections where the stations do (distances from the stop on the ground), and the difference is taken up by the middle of the hop.
	var span_a := minf(300.0, minf(real_len, dist) / 3.0)
	var warp := func(r: float) -> float:
		if r <= span_a:
			return r
		if r >= real_len - span_a:
			return r - real_len + dist
		return span_a + (r - span_a) * (dist - 2.0 * span_a) / maxf(real_len - 2.0 * span_a, 1.0)
	var r0 := 0.0
	for r in raw:
		var r1: float = r0 + float(r[1])
		secs.append([int(r[0]), float(warp.call(r1)) - float(warp.call(r0)), float(r[1])])
		r0 = r1
	if secs.is_empty():
		secs = _guess_secs(a, b, dist)
	single = is_single(a, b)
	var wat: Array = []          # (the rivers under the viaducts, in the ride's own distances)
	for w in water(a, b):
		wat.append([float(warp.call(float(w[0]))), float(w[1])])
	plan_scenes(secs, ss, pair_seed(a, b), kmin, kmax, dist, StationPlan.is_split(a, StationPlan.group_of(a, _line)), StationPlan.is_split(b, StationPlan.group_of(b, _line)), wat)


## The vertical profile. Two parts. The REAL one: the platform levels of the two stations (data/platform_levels.json, TfL FOI depth table via tubedepths, metres above Ordnance Datum) give how far the track
## climbs or falls between them ("dz" in data/line_geometry.json), spread over the stretch between the hand-over zones. On top of it a TYPICAL one (not surveyed): stations lie on a hump and the tubes
## between them dip - about 1 : 30 for a few hundred metres, 2 to 4 m deep for a mile-long hop - over the stretches of tunnel of the deep lines (none in the sub-surface lines' shallow tunnels or in the open).
## Both are zero over the platform and the stretch where the hand-overs happen; if the two together would be steeper than MAX_GRADE the whole profile is scaled down to fit.
## UG_GRADE=off switches both off, UG_GRADE=<metres> forces that dish depth (no real climb) over the whole ride (tests).
## Returns the climb per cell (radians) for the cells kmin..kmax.
func _plan_grade(a: String, b: String, line: String, dist: float, fade_in: float, fade_out: float, kmin: int, kmax: int) -> PackedFloat32Array:
	var n := kmax - kmin + 1
	var out := PackedFloat32Array()
	out.resize(n)
	var forced := OS.get_environment("UG_GRADE")
	if forced == "off":
		return out
	var w_int := dist - fade_in - fade_out
	if w_int < 120.0:
		return out
	var vr := clampf(w_int * 0.35, 40.0, 140.0)
	var depth := 0.0 if ss else clampf(w_int * 0.006, 0.5, 3.2)
	var rise := rise_between(a, b, line) if forced == "" else 0.0
	if forced != "":
		depth = forced.to_float()
	# where the track is in a tunnel
	var tun: Array = []
	var pos := 0.0
	for r in secs:
		if int(r[0]) == 1 or forced != "":
			tun.append([pos, pos + float(r[1])])
		pos += float(r[1])
	if forced != "":
		tun = [[0.0, dist]]
	if tun.is_empty() or depth == 0.0:
		depth = 0.0
	if depth == 0.0 and absf(rise) < 0.05:
		return out
	var ys := PackedFloat32Array()
	ys.resize(n + 1)
	var worst := 0.0
	for j in n + 1:
		var sj := float(kmin + j) * CELL - CELL * 0.5
		# the share of the stretch round sj (vr wide) that lies in a tunnel
		var cover := 0.0
		for t in tun:
			cover += maxf(0.0, minf(sj + vr * 0.5, t[1]) - maxf(sj - vr * 0.5, t[0]))
		var m := cover / vr
		var wn := smoothstep(fade_in, fade_in + vr, sj) * (1.0 - smoothstep(dist - fade_out - vr, dist - fade_out, sj))
		ys[j] = rise * smoothstep(fade_in, dist - fade_out, sj) - depth * m * wn
		if j > 0:
			worst = maxf(worst, absf(ys[j] - ys[j - 1]) / CELL)
	var fit := 1.0 if worst <= MAX_GRADE * 0.93 else MAX_GRADE * 0.93 / worst
	for i in n:
		out[i] = asin(clampf(fit * (ys[i + 1] - ys[i]) / CELL, -MAX_GRADE, MAX_GRADE))
	return out


## how far the platform at station `b` lies above the one at `a` (metres, from data/platform_levels.json via the hop's "dz"; where lines that share the hop have platforms at different heights, "dzl" has it per
## line and `line` picks); 0 where the data has none
static func rise_between(a: String, b: String, line := "") -> float:
	var pairs: Dictionary = data().get("pairs", {})
	var e: Dictionary = pairs.get(a + ">" + b, {})
	if e.has("dz"):
		var per: Dictionary = e.get("dzl", {})
		return float(per[line]) if per.has(line) else float(e["dz"])
	e = pairs.get(b + ">" + a, {})
	if e.has("dz"):
		var per2: Dictionary = e.get("dzl", {})
		return -(float(per2[line]) if per2.has(line) else float(e["dz"]))
	return 0.0


## the same for either direction of a pair of stations (which cuttings are brick-walled is chosen from it)
static func pair_seed(a: String, b: String) -> int:
	return (a + ">" + b if a < b else b + ">" + a).hash() & 0x7fffffff


## a hop the data does not have (the line's relation in OpenStreetMap lacks it): the open country between two surface stations, the tunnel between underground ones, and between a surface
## station and an underground one the open half then the tunnel half
static func _guess_secs(a: String, b: String, dist: float) -> Array:
	var ia := Net.station_ids.find(a)
	var ib := Net.station_ids.find(b)
	if ia < 0 or ib < 0:
		return [[1, dist]]
	var oa: bool = String(Net.stations[ia].get("kind", "deep")) == "surface"
	var ob: bool = String(Net.stations[ib].get("kind", "deep")) == "surface"
	if oa and ob:
		return [[0, dist]]
	if not oa and not ob:
		return [[1, dist]]
	return [[0 if oa else 1, dist * 0.5], [1 if oa else 0, dist * 0.5]]


## what the cells show for a line that runs through `p_secs` ([[sec code, metres], ...]); the cells from kmin to kmax
func plan_scenes(p_secs: Array, p_ss: bool, seed: int, kmin: int, kmax: int, p_dist := -1.0, split_a := false, split_b := false, p_water := []) -> void:
	secs = p_secs
	ss = p_ss
	_scenes = RunScenery.cell_scenes(secs, ss, seed, kmin, kmax, p_dist, single, split_a, split_b, p_water)


## RunScenery's scene number of cell k (the bore beyond the cells that were planned)
func cell_scene(k: int) -> int:
	var i := k - _kmin
	if i < 0:
		return _scenes[0] if not _scenes.is_empty() else RunScenery.BORE
	if i >= _scenes.size():
		return _scenes[_scenes.size() - 1] if not _scenes.is_empty() else RunScenery.BORE
	return _scenes[i]


## how far the other track of the pair lies from this one at path distance s (RunScenery: the station's spacing near the stops and the tunnel mouths, narrowing to the line's between; the cells' own levels, linear across a cell)
func spacing_at(s: float) -> float:
	var k := int(roundf(s / CELL))
	var sc := cell_scene(k)
	if (sc & RunScenery.PAIR) == 0:
		return RunScenery.TRACK_SPACING
	var f := clampf((s - (float(k) * CELL - CELL * 0.5)) / CELL, 0.0, 1.0)
	return lerpf(RunScenery.spacing_of_level((sc >> 13) & 15), RunScenery.spacing_of_level((sc >> 17) & 15), f)


## [real length, headings in radians at 0, step, 2 step ... length] of the track from a to b, or [] when unknown. Falls back to the other direction's track, reversed.
static func profile(a: String, b: String) -> Array:
	var pairs: Dictionary = data().get("pairs", {})
	var e: Dictionary = pairs.get(a + ">" + b, {})
	if not e.is_empty():
		var hs: Array = []
		for v in e["h"]:
			hs.append(deg_to_rad(float(v) / 10.0))
		return [float(e["len"]), hs]
	e = pairs.get(b + ">" + a, {})
	if e.is_empty():
		return []
	# the same track travelled the other way: heading(s) = h(len - s) - h(len)
	var raw: Array = e["h"]
	var step: float = data().get("step", 20.0)
	var L: float = e["len"]
	var hl := deg_to_rad(float(raw[raw.size() - 1]) / 10.0)
	var n := int(floor(L / step))
	var hs2: Array = []
	for i in n + 1:
		hs2.append(_heading_at_raw(raw, step, L, L - float(i) * step) - hl)
	var tail := L - float(n) * step
	if tail > 1.0:
		hs2.append(_heading_at_raw(raw, step, L, 0.0) - hl)
	return [L, hs2]


static func _heading_at_raw(raw: Array, step: float, L: float, s: float) -> float:
	var hs: Array = []
	for v in raw:
		hs.append(deg_to_rad(float(v) / 10.0))
	return _heading_at(hs, step, L, s)


## heading at distance s from samples every `step` metres (the last one at `L`)
static func _heading_at(hs: Array, step: float, L: float, s: float) -> float:
	s = clampf(s, 0.0, L)
	var n := hs.size()
	var full := int(floor(L / step))               # samples 0..full are on the step grid; a last one (if any) is at L
	var i := mini(int(floor(s / step)), full)
	if i >= n - 1:
		return hs[n - 1]
	var s0 := float(i) * step
	var s1 := float(i + 1) * step if i + 1 <= full else L
	return lerpf(hs[i], hs[i + 1], clampf((s - s0) / maxf(s1 - s0, 0.001), 0.0, 1.0))


func _build(ks: PackedFloat32Array, dist: float, kmin := 0) -> void:
	length = dist
	kappa = ks
	_kmin = kmin
	var n := kappa.size()
	pitch = _plan_pitch if _plan_pitch.size() == n else PackedFloat32Array()
	if pitch.size() != n:
		pitch.resize(n)
	_th.resize(n + 1)
	_p.resize(n + 1)
	_th[0] = 0.0
	_p[0] = Vector3.ZERO
	for i in n:
		var q := _step(_th[i], _p[i], kappa[i], CELL, pitch[i])
		_th[i + 1] = q[0]
		_p[i + 1] = q[1]
	# the frame of the path is the one the track has at distance 0
	_anchor = Transform3D.IDENTITY
	_anchor = _raw_pose(0.0).affine_inverse()


## heading and position after u metres of curvature kk and climb pc (radians) from heading th0 at p0
static func _step(th0: float, p0: Vector3, kk: float, u: float, pc := 0.0) -> Array:
	var h := u * cos(pc)               # (the distance covered on the ground)
	var dy := u * sin(pc)
	if absf(kk) < 1e-9:
		return [th0, p0 + Vector3(cos(th0) * h, dy, -sin(th0) * h)]
	var th1 := th0 + kk * h
	return [th1, p0 + Vector3((sin(th1) - sin(th0)) / kk, dy, (cos(th1) - cos(th0)) / kk)]


func is_straight() -> bool:
	for k in kappa:
		if absf(k) > 1e-9:
			return false
	return is_level()


## no climb or dip anywhere
func is_level() -> bool:
	for g in pitch:
		if absf(g) > 1e-9:
			return false
	return true


func cell_count() -> int:
	return kappa.size()


## the first and the last cell index
func k_first() -> int:
	return _kmin


func k_last() -> int:
	return _kmin + kappa.size() - 1


## the curvature class (-MAX_CLASS..MAX_CLASS) of the cell centred at k * CELL
func cell_class(k: int) -> int:
	var i := k - _kmin
	if i < 0 or i >= kappa.size():
		return 0
	return int(roundf(kappa[i] / Q))


func _raw_pose(s: float) -> Transform3D:
	var n := kappa.size()
	var s_start := float(_kmin) * CELL - CELL * 0.5
	var i := int(floor((s - s_start) / CELL))
	if i < 0:
		return Transform3D(Basis.IDENTITY, Vector3(s - s_start, 0.0, 0.0))
	if i >= n:
		var th := _th[n]
		return Transform3D(Basis(Vector3.UP, th), _p[n] + Vector3(cos(th), 0.0, -sin(th)) * (s - s_start - float(n) * CELL))
	var pc: float = pitch[i]
	var q := _step(_th[i], _p[i], kappa[i], s - s_start - float(i) * CELL, pc)
	return Transform3D(Basis(Vector3.UP, q[0]) * Basis(Vector3(0.0, 0.0, 1.0), pc), q[1])


## the pose of the track at distance s: origin on the centre line at the path's level 0, +x along the track, +z to the right
func pose(s: float) -> Transform3D:
	return _anchor * _raw_pose(s)


## heading of the track at distance s relative to the start (radians, + = left)
func theta(s: float) -> float:
	return _theta_raw(s) - _theta_raw(0.0)


func _theta_raw(s: float) -> float:
	var n := kappa.size()
	var s_start := float(_kmin) * CELL - CELL * 0.5
	var i := int(floor((s - s_start) / CELL))
	if i < 0:
		return 0.0
	if i >= n:
		return _th[n]
	return _th[i] + kappa[i] * (s - s_start - float(i) * CELL)
