#!/usr/bin/env python3
"""Line colours that stay distinguishable for colour-blind players -> data/line_palettes.json.

For each kind of colour vision deficiency (protanopia, deuteranopia, tritanopia: dichromacy, Machado et al. 2009 matrices at full severity, applied in linear RGB) the colours of the
eleven Underground lines are moved (a stochastic hill climb in CIELAB) until the closest pair of lines, *as that player sees them*, is as far apart as possible, without wandering far
from the original colours (the brand colours stay recognisable for everybody else). Deterministic (seeded). Prints the before / after minimum distances.
    python3 tools/gen_cvd_palettes.py
Colours are only part of it: every sign, board and map label also carries the line's name."""
import json
import math
import os
import random

import numpy as np

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
LINES = json.load(open(os.path.join(ROOT, "data", "network.json")))["lines"]

SIM = {
    "protanopia": np.array([[0.152286, 1.052583, -0.204868], [0.114503, 0.786281, 0.099216], [-0.003882, -0.048116, 1.051998]]),
    "deuteranopia": np.array([[0.367322, 0.860646, -0.227968], [0.280085, 0.672501, 0.047413], [-0.011820, 0.042940, 0.968881]]),
    "tritanopia": np.array([[1.255528, -0.076749, -0.178779], [-0.078411, 0.930809, 0.147602], [0.004733, 0.691367, 0.303900]]),
}
M_RGB2XYZ = np.array([[0.4124564, 0.3575761, 0.1804375], [0.2126729, 0.7151522, 0.0721750], [0.0193339, 0.1191920, 0.9503041]])
WHITE = np.array([0.95047, 1.0, 1.08883])


def srgb_to_lin(c):
    c = np.asarray(c, float)
    return np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4)


def lin_to_srgb(c):
    c = np.clip(np.asarray(c, float), 0, 1)
    return np.where(c <= 0.0031308, c * 12.92, 1.055 * c ** (1 / 2.4) - 0.055)


def lin_to_lab(lin):
    xyz = M_RGB2XYZ @ lin / WHITE
    f = np.where(xyz > 216 / 24389, np.cbrt(xyz), (24389 / 27 * xyz + 16) / 116)
    return np.array([116 * f[1] - 16, 500 * (f[0] - f[1]), 200 * (f[1] - f[2])])


def lab_to_lin(lab):
    fy = (lab[0] + 16) / 116
    fx = fy + lab[1] / 500
    fz = fy - lab[2] / 200
    f = np.array([fx, fy, fz])
    xyz = np.where(f ** 3 > 216 / 24389, f ** 3, (116 * f - 16) / (24389 / 27)) * WHITE
    return np.linalg.inv(M_RGB2XYZ) @ xyz


def in_gamut(lab):
    lin = lab_to_lin(lab)
    return bool(np.all(lin >= -1e-4) and np.all(lin <= 1 + 1e-4))


def hex_to_srgb(h):
    h = h.lstrip("#")
    return np.array([int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)])


def srgb_to_hex(c):
    return "#%02x%02x%02x" % tuple(int(round(v * 255)) for v in np.clip(c, 0, 1))


def simulate_lab(lab, kind):
    lin = np.clip(lab_to_lin(lab), 0, 1)
    return lin_to_lab(np.clip(SIM[kind] @ lin, 0, 1)) if kind else lab


def min_pair(labs, kind):
    sims = [simulate_lab(l, kind) for l in labs]
    best = 1e9
    for i in range(len(sims)):
        for j in range(i + 1, len(sims)):
            best = min(best, float(np.linalg.norm(sims[i] - sims[j])))
    return best


TARGET = 26.0          # every pair of lines at least this far apart (CIELAB distance) as the colour-blind player sees them


def score(labs, orig, kind, stay):
    """higher is better: as little drift from the brand colours as possible, with every pair at least TARGET apart as seen (a heavy penalty on each pair that is closer)"""
    sims = [simulate_lab(l, kind) for l in labs]
    pen = 0.0
    for i in range(len(sims)):
        for j in range(i + 1, len(sims)):
            d = float(np.linalg.norm(sims[i] - sims[j]))
            if d < TARGET:
                pen += (TARGET - d) ** 2
    drift = sum(float(np.linalg.norm(labs[i] - orig[i])) for i in range(len(labs))) / len(labs)
    return -(drift + 0.6 * pen)


def optimise(kind, ids, orig, iters=40000, stay=0.0, seed=7):
    rnd = random.Random(seed)
    cur = [o.copy() for o in orig]
    cur_s = score(cur, orig, kind, stay)
    best, best_s = [c.copy() for c in cur], cur_s
    for it in range(iters):
        i = rnd.randrange(len(cur))
        step = 10.0 * (1 - it / iters) + 0.8
        cand = cur[i] + np.array([rnd.gauss(0, step), rnd.gauss(0, step), rnd.gauss(0, step)])
        if cand[0] < 6 or cand[0] > 96 or not in_gamut(cand):
            continue
        old = cur[i]
        cur[i] = cand
        s = score(cur, orig, kind, stay)
        temp = 4.0 * (1 - it / iters) + 0.05
        if s > cur_s or rnd.random() < math.exp((s - cur_s) / temp):
            cur_s = s
            if s > best_s:
                best_s, best = s, [c.copy() for c in cur]
        else:
            cur[i] = old
    return best


def main():
    ids = sorted(LINES)
    orig = [lin_to_lab(srgb_to_lin(hex_to_srgb(LINES[i]["color"]))) for i in ids]
    out = {"_comment": "generated by tools/gen_cvd_palettes.py: line colours that stay distinguishable under protanopia, deuteranopia and tritanopia"}
    for kind in SIM:
        before = min_pair(orig, kind)
        new = optimise(kind, ids, orig)
        after = min_pair(new, kind)
        print("%-13s closest pair as seen: %5.1f -> %5.1f" % (kind, before, after))
        out[kind] = {i: srgb_to_hex(lin_to_srgb(np.clip(lab_to_lin(l), 0, 1))) for i, l in zip(ids, new)}
        for i, l in zip(ids, new):
            print("    %-18s %s -> %s" % (i, LINES[i]["color"], out[kind][i]))
    json.dump(out, open(os.path.join(ROOT, "data", "line_palettes.json"), "w"), indent=1)


if __name__ == "__main__":
    main()
