class_name PersonModel
extends Node3D
## A single animated commuter, built from assets/people (generated by tools/blender/people/*).
##
##   var p := PersonModel.create(index, seed)      # index in [0, PersonModel.count()), seed = per-instance variation
##   add_child(p)
##   p.play(&"idle_stand_1")                        # or p.set_locomotion_speed(1.3) while moving
##   p.set_detail(PersonModel.DETAIL_NEAR .. DETAIL_HIDDEN)   # distance LOD, see below
##
## Node layout:  PersonModel (Node3D, faces -Z, feet at y=0)
##                 +- Model (glb root)  / Armature / Skeleton3D / <mesh, 3-4 surfaces>
##                 +- AnimationPlayer   (root_node = Armature; shared AnimationLibrary, manual advance)
##                 +- [BoneAttachment3D + bag mesh]  (optional)
##
## The mesh has one MeshInstance3D with surfaces named skin / face / outfit / hair.  Their materials are
## ShaderMaterials built once per character index and shared by all instances; per instance variation
## (clothes / hair / skin tint) is done with instance uniforms so no material is ever duplicated.

const MANIFEST_PATH := "res://assets/people/people_manifest.json"
const ANIMS_PATH := "res://assets/people/anims/people_anims.res"
const META_PATH := "res://assets/people/anims/anims_meta.json"
const SHADER_DIR := "res://assets/people/shaders/"
const TEX_DIR := "res://assets/people/tex/"
const BAG_DIR := "res://assets/people/bags/"

## detail levels for set_detail()
const DETAIL_NEAR := 0      ## every frame, shadows on
const DETAIL_MID := 1       ## animate at 30 Hz
const DETAIL_FAR := 2       ## animate at 15 Hz, no shadow
const DETAIL_VERY_FAR := 3  ## animate at 8 Hz, no shadow, coarser mesh LOD
const DETAIL_FROZEN := 4    ## pose frozen (no animation cost at all)
const DETAIL_HIDDEN := 5    ## hidden (no rendering)
const _TICK_HZ := [0.0, 30.0, 15.0, 8.0, 0.0, 0.0]

static var _manifest: Dictionary = {}
static var _chars: Array = []
static var _anim_lib: AnimationLibrary
static var _meta: Dictionary = {}
static var _clips: Dictionary = {}
static var _loco_clips: Array = []       # [{name, speed}] sorted by stride speed
static var _packed: Dictionary = {}
static var _mats: Dictionary = {}
static var _shared_tex: Dictionary = {}
static var _bag_meshes: Dictionary = {}
static var _bag_mat: ShaderMaterial
static var _loaded := false

## When the scene person_model.tscn is instanced directly (instead of PersonModel.create) set these in the inspector.
@export var auto_index := -1
@export var auto_seed := 0

var index := 0
var variation_seed := 0
var info: Dictionary = {}
var skeleton: Skeleton3D
var mesh_instance: MeshInstance3D
var anim_player: AnimationPlayer
var model_root: Node3D
var leg_scale := 1.0          ## this character's leg length / reference leg length
var detail_level := 0
var current_clip: StringName = &""
var manual_tick := false      ## set true if a crowd manager calls tick(delta) itself
var _accum := 0.0
var _dirty := false
var _speed_scale := 1.0
var _loco_target := -1.0
var _loco_clip: StringName = &""
var _gait_mask: Array = []
var _rng := RandomNumberGenerator.new()
var _bag_node: Node3D
var _bag_hang := false
var _bag_bone := -1
var _bag_offset := Vector3.ZERO
var _height_jitter := 1.0
var _finger_bones: PackedInt32Array = PackedInt32Array()


func _ready() -> void:
	if auto_index >= 0 and model_root == null:
		build(auto_index, auto_seed)


# ------------------------------------------------------------------------------ static API
static func _ensure_loaded() -> void:
	if _loaded:
		return
	_loaded = true
	var f := FileAccess.open(MANIFEST_PATH, FileAccess.READ)
	if f:
		_manifest = JSON.parse_string(f.get_as_text())
		_chars = _manifest.get("characters", [])
	else:
		push_error("PersonModel: manifest missing: " + MANIFEST_PATH)
	if ResourceLoader.exists(ANIMS_PATH):
		_anim_lib = load(ANIMS_PATH)
	var mf := FileAccess.open(META_PATH, FileAccess.READ)
	if mf:
		_meta = JSON.parse_string(mf.get_as_text())
		_clips = _meta.get("clips", {})
		for n in _clips:
			var c: Dictionary = _clips[n]
			if c.get("kind", "") == "locomotion":
				_loco_clips.append({"name": StringName(n), "speed": float(c["stride_speed_mps"])})
		_loco_clips.sort_custom(func(a, b): return a["speed"] < b["speed"])


## Start loading every character (scene + textures) and the shared textures on worker threads: loading them on first use took about 140 ms each on the main thread
## (6 s for all 36). Call at start-up; `preload_ready()` says when everything is in.
static func preload_async() -> void:
	_ensure_loaded()
	for c in _chars:
		_request(String(c["file"]))
		var ms: Dictionary = c.get("material_slots", {})
		for k in ["skin", "face", "outfit", "outfit_normal", "hair"]:
			_request(String(ms.get(k, "")))
	for n in ["skin_detail_n.png", "cloth_detail_n.png"]:
		_request(TEX_DIR + n)
	for sh in ["person_skin.gdshader", "person_face.gdshader", "person_outfit.gdshader", "person_hair.gdshader"]:
		_request(SHADER_DIR + sh)
	_request(ANIMS_PATH)


static func _request(path: String) -> void:
	if path != "" and ResourceLoader.exists(path):
		ResourceLoader.load_threaded_request(path, "", true)


static func preload_ready() -> bool:
	_ensure_loaded()
	var paths: Array = []
	for c in _chars:
		paths.append(String(c["file"]))
		var ms: Dictionary = c.get("material_slots", {})
		for k in ["skin", "face", "outfit", "outfit_normal", "hair"]:
			if String(ms.get(k, "")) != "":
				paths.append(String(ms[k]))
	for p in paths:
		var st := ResourceLoader.load_threaded_get_status(p)
		if st == ResourceLoader.THREAD_LOAD_IN_PROGRESS:
			return false
	return true


static func count() -> int:
	_ensure_loaded()
	return _chars.size()


static func character_info(i: int) -> Dictionary:
	_ensure_loaded()
	return _chars[i % _chars.size()]


static func clip_meta(clip: StringName) -> Dictionary:
	_ensure_loaded()
	return _clips.get(String(clip), {})


static func has_clip(clip: StringName) -> bool:
	_ensure_loaded()
	return _anim_lib != null and _anim_lib.has_animation(clip)


static func create(index: int, seed: int = 0) -> PersonModel:
	_ensure_loaded()
	var p := PersonModel.new()
	p.name = "Person"
	p.build(index, seed)
	return p


static func _tex(path: String) -> Texture2D:
	if path == "":
		return null
	return load(path) as Texture2D


static func _shared(name: String) -> Texture2D:
	if not _shared_tex.has(name):
		_shared_tex[name] = load(TEX_DIR + name)
	return _shared_tex[name]


static func _make_shader_mat(shader_name: String) -> ShaderMaterial:
	var m := ShaderMaterial.new()
	m.shader = load(SHADER_DIR + shader_name)
	return m


## Builds (once per character index) the four shader materials and assigns them to the shared mesh.
static func _prepare_mesh_materials(i: int, mesh: Mesh) -> void:
	if _mats.has(i):
		return
	var c: Dictionary = _chars[i]
	var ms: Dictionary = c["material_slots"]
	var out := {}
	var skin := _make_shader_mat("person_skin.gdshader")
	skin.set_shader_parameter("albedo_tex", _tex(ms["skin"]))
	skin.set_shader_parameter("detail_normal", _shared("skin_detail_n.png"))
	out["skin"] = skin
	var face := _make_shader_mat("person_face.gdshader")
	face.set_shader_parameter("albedo_tex", _tex(ms["face"]))
	out["face"] = face
	var outfit := _make_shader_mat("person_outfit.gdshader")
	outfit.set_shader_parameter("albedo_tex", _tex(ms["outfit"]))
	outfit.set_shader_parameter("cloth_detail", _shared("cloth_detail_n.png"))
	if ms.get("outfit_normal", "") != "":
		outfit.set_shader_parameter("normal_tex", _tex(ms["outfit_normal"]))
		outfit.set_shader_parameter("use_normal_tex", true)
	out["outfit"] = outfit
	if ms.get("hair", "") != "":
		var hair := _make_shader_mat("person_hair.gdshader")
		hair.set_shader_parameter("albedo_tex", _tex(ms["hair"]))
		out["hair"] = hair
	_mats[i] = out
	for s in mesh.get_surface_count():
		var mat: Material = mesh.surface_get_material(s)
		var n := mat.resource_name if mat else ""
		if out.has(n):
			(mesh as ArrayMesh).surface_set_material(s, out[n])
		else:
			push_warning("PersonModel: unknown surface material '%s' in %s" % [n, c["id"]])


# ------------------------------------------------------------------------------ construction
func build(idx: int, seed: int) -> void:
	_ensure_loaded()
	index = idx % maxi(_chars.size(), 1)
	variation_seed = seed
	info = _chars[index]
	_rng.seed = hash(str(seed) + "_" + str(index)) if seed != 0 else 0
	if not _packed.has(index):
		_packed[index] = load(info["file"])
	model_root = (_packed[index] as PackedScene).instantiate()
	model_root.name = "Model"
	add_child(model_root)
	skeleton = _find_skeleton(model_root)
	mesh_instance = _find_mesh(model_root)
	if mesh_instance:
		_prepare_mesh_materials(index, mesh_instance.mesh)
		mesh_instance.extra_cull_margin = 0.4
		mesh_instance.gi_mode = GeometryInstance3D.GI_MODE_DISABLED
	# leg scale relative to the reference skeleton the animations were authored on
	var ref_leg: float = float(_meta.get("ref", {}).get("leg_length", info["leg_length_m"]))
	leg_scale = float(info["leg_length_m"]) / ref_leg
	if skeleton:
		skeleton.motion_scale = float(info["pelvis_height_m"]) / float(_meta.get("ref", {}).get("pelvis_height", info["pelvis_height_m"]))
	# animation player (shared library)
	anim_player = AnimationPlayer.new()
	anim_player.name = "AnimationPlayer"
	add_child(anim_player)
	anim_player.root_node = anim_player.get_path_to(skeleton.get_parent()) if skeleton else NodePath("..")
	anim_player.callback_mode_process = AnimationMixer.ANIMATION_CALLBACK_MODE_PROCESS_MANUAL
	if _anim_lib:
		anim_player.add_animation_library(&"", _anim_lib)
	_apply_variation()
	set_process(false)


func _find_skeleton(n: Node) -> Skeleton3D:
	if n is Skeleton3D:
		return n
	for c in n.get_children():
		var r := _find_skeleton(c)
		if r:
			return r
	return null


func _find_mesh(n: Node) -> MeshInstance3D:
	if n is MeshInstance3D:
		return n
	for c in n.get_children():
		var r := _find_mesh(c)
		if r:
			return r
	return null


static func _pick_palette(rng: RandomNumberGenerator, name: String) -> Color:
	var pal: Array = _manifest.get("palettes", {}).get(name, [])
	if pal.is_empty():
		return Color.WHITE
	var total := 0.0
	for e in pal:
		total += float(e[1])
	var r := rng.randf() * total
	for e in pal:
		r -= float(e[1])
		if r <= 0.0:
			return Color(e[2][0], e[2][1], e[2][2])
	var e2 = pal[pal.size() - 1]
	return Color(e2[2][0], e2[2][1], e2[2][2])


func _jitter(c: Color, rng: RandomNumberGenerator, amt: float) -> Color:
	var k := 1.0 + rng.randf_range(-amt, amt)
	return Color(clampf(c.r * k, 0, 1), clampf(c.g * k, 0, 1), clampf(c.b * k, 0, 1))


## per-instance variation: instance uniforms only (no new materials)
func _apply_variation() -> void:
	if mesh_instance == null:
		return
	var rng := _rng
	var slots: Dictionary = info["tint_slots"]
	var randomize_ := variation_seed != 0
	var white := Color(1, 1, 1)
	var tints := {"top": white, "bottom": white, "outer": white}
	for s in tints.keys():
		if slots.has(s) and slots[s].get("recolor", false):
			var d: Array = slots[s]["default"]
			var col := Color(d[0], d[1], d[2])
			if randomize_ and rng.randf() < 0.6:
				col = _jitter(_pick_palette(rng, slots[s]["palette"]), rng, 0.12)
			elif randomize_:
				col = _jitter(col, rng, 0.08)
			# tint is relative to the garment's own mean colour, which the atlas normalised away
			tints[s] = col
	mesh_instance.set_instance_shader_parameter("tint_top", tints["top"])
	mesh_instance.set_instance_shader_parameter("tint_bottom", tints["bottom"])
	mesh_instance.set_instance_shader_parameter("tint_outer", tints["outer"])
	var ht = info.get("hair_tint", null)
	var hcol := Color(0.1, 0.07, 0.05)
	if ht != null:
		hcol = Color(ht[0], ht[1], ht[2])
		if randomize_ and int(info["age"]) < 50 and rng.randf() < 0.35:
			hcol = _jitter(_pick_palette(rng, "hair"), rng, 0.2)
		elif randomize_:
			hcol = _jitter(hcol, rng, 0.15)
	mesh_instance.set_instance_shader_parameter("hair_tint", hcol)
	var sk := 1.0
	var warm := 0.0
	if randomize_:
		sk = rng.randf_range(0.9, 1.07)
		warm = rng.randf_range(-0.03, 0.03)
	mesh_instance.set_instance_shader_parameter("skin_tint", Color(sk * (1.0 + warm), sk, sk * (1.0 - warm)))
	if randomize_:
		_height_jitter = rng.randf_range(0.98, 1.03)
		scale = Vector3.ONE * _height_jitter
	# personal gait: hide some locomotion clips so neighbours do not all move identically
	_gait_mask.clear()
	if randomize_ and _loco_clips.size() > 3:
		for lc in _loco_clips:
			_gait_mask.append(rng.randf() < 0.7)
		# always keep the slowest, fastest
		_gait_mask[0] = true
		_gait_mask[_gait_mask.size() - 1] = true
	if info.get("has_bag", false):
		set_bag(true)


## Add / remove the character's carried bag (backpack / shoulder bag / briefcase / handbag / tote).
## Backpack and shoulder bag ride rigidly on the torso; hand-carried bags hang vertically from the right hand.
func set_bag(enabled: bool, kind: String = "") -> void:
	if _bag_node:
		_bag_node.queue_free()
		_bag_node = null
	_bag_hang = false
	if not enabled or skeleton == null:
		return
	var k := kind if kind != "" else String(info.get("bag", ""))
	if k == "":
		k = "backpack"
	var path := BAG_DIR + "bag_%s.glb" % k
	if not ResourceLoader.exists(path):
		return
	if not _bag_meshes.has(k):
		_bag_meshes[k] = load(path)
	var inst: Node3D = (_bag_meshes[k] as PackedScene).instantiate()
	var s := float(info["height_m"]) / 1.75
	var rng := _rng
	var col := Color(0.06, 0.06, 0.07)
	if variation_seed != 0:
		col = _jitter(_pick_palette(rng, "outer"), rng, 0.15)
	if k in ["backpack", "shoulder"]:
		var attach := BoneAttachment3D.new()
		attach.name = "BagAttachment"
		skeleton.add_child(attach)
		attach.bone_name = "spine_03" if k == "backpack" else "pelvis"
		attach.add_child(inst)
		var bi := skeleton.find_bone(attach.bone_name)
		var rest_global: Transform3D = skeleton.get_bone_global_rest(bi)
		var off := Vector3(0, -0.03, 0.185) if k == "backpack" else Vector3(0.23, -0.06, 0.03)
		# the bag models are built with the wearer's chest on their -Y side, which glTF turns into +Z; people face -Z, so turn the bag round
		# (without this the shoulder straps stick out of the back of the pack)
		var desired := Transform3D(Basis(Vector3.UP, PI).scaled(Vector3.ONE * s), rest_global.origin + off * s)
		inst.transform = rest_global.affine_inverse() * desired
		_bag_node = attach
	else:
		add_child(inst)
		inst.scale = Vector3.ONE * s
		_bag_node = inst
		_bag_hang = true
		_bag_bone = skeleton.find_bone("hand_r")
		_bag_offset = Vector3(0.0, -0.09, 0.0) * s
		_update_bag()
	if _bag_mat == null:
		_bag_mat = _make_shader_mat("person_bag.gdshader")
		_bag_mat.set_shader_parameter("detail", _shared("bag_detail.png"))
	for mi in inst.find_children("*", "MeshInstance3D", true, false):
		(mi as MeshInstance3D).material_override = _bag_mat
		(mi as MeshInstance3D).set_instance_shader_parameter("bag_tint", col)


func _update_bag() -> void:
	if _bag_hang and _bag_node and skeleton:
		var hp := skeleton.get_bone_global_pose(_bag_bone).origin
		# skeleton space -> PersonModel space (skeleton and model are not rotated relative to us)
		_bag_node.position = model_root.transform * (skeleton.get_parent().transform * (skeleton.transform * hp)) + _bag_offset


# ------------------------------------------------------------------------------ animation API
## Play a clip from the shared library.  `speed` multiplies playback speed.
func play(anim: StringName, blend: float = 0.25, speed: float = 1.0) -> void:
	if anim_player == null or not anim_player.has_animation(anim):
		return
	_loco_target = -1.0
	_play_internal(anim, blend, speed)


## Queue a clip to start when the current (non-looping) clip ends, e.g. play(&"sit_down"); queue(&"sit_idle_1").
func queue(anim: StringName) -> void:
	if anim_player and anim_player.has_animation(anim):
		anim_player.queue(anim)


## Metadata of a clip: duration, loop, kind, stride_speed_mps (locomotion), yaw_delta_deg (turns) ...
func clip_info(anim: StringName) -> Dictionary:
	return _clips.get(String(anim), {})


func _play_internal(anim: StringName, blend: float, speed: float) -> void:
	var same := anim == current_clip and anim_player.is_playing()
	if same:
		anim_player.speed_scale = speed
		_speed_scale = speed
		return
	var phase := 0.0
	var keep_phase := false
	if current_clip != &"" and anim_player.is_playing() and _is_loco(current_clip) and _is_loco(anim):
		var cl := anim_player.current_animation_length
		if cl > 0.0:
			phase = anim_player.current_animation_position / cl
			keep_phase = true
	var had_fingers: bool = _clips.get(String(current_clip), {}).get("fingers", false)
	var has_fingers: bool = _clips.get(String(anim), {}).get("fingers", false)
	current_clip = anim
	anim_player.play(anim, blend, speed)
	if had_fingers and not has_fingers:
		_release_fingers(blend + 0.05)
	_speed_scale = speed
	if keep_phase:
		anim_player.seek(phase * anim_player.current_animation_length, false)
	if not manual_tick and detail_level < DETAIL_FROZEN:
		set_process(true)
	# make sure the first frame is applied even at low tick rates
	_dirty = true


## grip clips (holds / phone) animate finger bones; other clips do not, so return them to the relaxed rest pose
func _release_fingers(delay: float) -> void:
	if delay > 0.0 and is_inside_tree():
		await get_tree().create_timer(delay).timeout
	if skeleton == null or not is_instance_valid(skeleton):
		return
	if _clips.get(String(current_clip), {}).get("fingers", false):
		return
	if _finger_bones.is_empty():
		for f in ["index", "middle", "ring", "pinky", "thumb"]:
			for k in ["01", "02", "03"]:
				for side in ["l", "r"]:
					var b := skeleton.find_bone("%s_%s_%s" % [f, k, side])
					if b >= 0:
						_finger_bones.append(b)
	for b in _finger_bones:
		skeleton.reset_bone_pose(b)


func _is_loco(n: StringName) -> bool:
	return _clips.get(String(n), {}).get("kind", "") == "locomotion"


func current_length() -> float:
	return anim_player.current_animation_length if anim_player else 0.0


## Drive locomotion animation from the actual ground speed in m/s: chooses walk_slow / walk_normal / walk_brisk / variants
## and scales the playback speed so the feet do not slide.  mps < 0.12 falls back to idle_stand_1.
func set_locomotion_speed(mps: float) -> void:
	if anim_player == null or _loco_clips.is_empty():
		return
	_loco_target = mps
	if mps < 0.12:
		if current_clip != &"idle_stand_1" and _is_loco(current_clip) or current_clip == &"":
			_play_internal(&"idle_stand_1", 0.3, 1.0)
		return
	var s := mps / maxf(leg_scale, 0.3)      # speed on the reference skeleton
	var best := -1
	var best_err := 1e9
	for k in _loco_clips.size():
		if not _gait_mask.is_empty() and not _gait_mask[k]:
			continue
		var err := absf(log(s / _loco_clips[k]["speed"]))
		# hysteresis: prefer the clip we are already playing
		if _loco_clips[k]["name"] == _loco_clip:
			err -= 0.12
		if err < best_err:
			best_err = err
			best = k
	var c: Dictionary = _loco_clips[best]
	var sp := clampf(s / c["speed"], 0.55, 1.6)
	_loco_clip = c["name"]
	_play_internal(c["name"], 0.3, sp)
	anim_player.speed_scale = sp
	_speed_scale = sp


func is_locomoting() -> bool:
	return _loco_target > 0.12


func set_detail(level: int) -> void:
	level = clampi(level, 0, DETAIL_HIDDEN)
	if level == detail_level:
		return
	detail_level = level
	if mesh_instance:
		mesh_instance.visible = level < DETAIL_HIDDEN
		mesh_instance.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_ON if level <= DETAIL_MID else GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		mesh_instance.lod_bias = 1.0 if level < DETAIL_VERY_FAR else 2.5
	if _bag_node:
		_bag_node.visible = level < DETAIL_HIDDEN
	set_process(not manual_tick and level < DETAIL_FROZEN and anim_player != null and anim_player.is_playing())
	_dirty = true


func _process(delta: float) -> void:
	tick(delta)


## Advance the animation by `delta` seconds, honouring the detail level tick rate.
func tick(delta: float) -> void:
	if anim_player == null or detail_level >= DETAIL_FROZEN:
		return
	_accum += delta
	var hz: float = _TICK_HZ[detail_level]
	if hz > 0.0 and _accum < 1.0 / hz and not _dirty:
		return
	anim_player.advance(_accum)
	var ca := anim_player.current_animation
	if ca != "" and StringName(ca) != current_clip:
		current_clip = StringName(ca)      # a queued clip has started
	if _bag_hang:
		_update_bag()
	_accum = 0.0
	_dirty = false
